coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: 80%
        informational: true

comment:
  layout: "header, diff, flags, components"
  behavior: default
  require_changes: false
